const palette = {
  navy: "#1A2340",
  navyMid: "#243058",
  navyLight: "#2E3D6E",
  softBlue: "#4A6898",
  rose: "#C97B84",
  roseDark: "#A05A65",
  roseLight: "#E8A5AD",
  cream: "#F5EDE8",
  creamDark: "#EAD9D1",
  slate: "#8A9BB5",
  slateLight: "#B8C6DA",
  green: "#5C9E8A",
  greenLight: "#7BBFAD",
  amber: "#C4903A",
  surface: "#FFFFFF",
  surfaceSecondary: "#F0F4F8",
  border: "#E1E8F0",
  textPrimary: "#1A2340",
  textSecondary: "#4A5568",
  textTertiary: "#718096",
  nordicBlue: "#E6F0F9",
  nordicIce: "#F4F9FF",
};

export default {
  palette,
  light: {
    text: palette.textPrimary,
    textSecondary: palette.textSecondary,
    textTertiary: palette.textTertiary,
    background: palette.nordicIce,
    surface: palette.surface,
    border: palette.border,
    tint: palette.softBlue,
    tabIconDefault: palette.slateLight,
    tabIconSelected: palette.softBlue,
    accent: palette.softBlue,
    accentDark: palette.navy,
    accentLight: palette.slateLight,
    success: palette.green,
    warning: palette.amber,
    navy: palette.navy,
    navyMid: palette.navyMid,
    cream: palette.cream,
    slate: palette.slate,
    primaryBtn: palette.softBlue,
    badgeBg: palette.nordicBlue,
    badgeText: palette.navy,
  },
  dark: {
    text: "#F0F4FF",
    textSecondary: "#9AAAC8",
    textTertiary: "#6B80A0",
    background: "#0D1220",
    surface: "#1A2340",
    border: "#2E3D6E",
    tint: "#8AAEE8",
    tabIconDefault: "#3D5080",
    tabIconSelected: "#8AAEE8",
    accent: palette.roseLight,
    accentDark: palette.rose,
    accentLight: "#F0B8C0",
    success: palette.greenLight,
    warning: "#DBA84A",
    navy: "#0D1220",
    navyMid: "#1A2340",
    cream: "#2E3D6E",
    slate: palette.slate,
    primaryBtn: "#5B85C8",
    badgeBg: "#243058",
    badgeText: "#E0E8FF",
  },
};
